# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-Capture
version:      0.01
version_from: lib/IPC/Capture.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Base:                   0
    Data::Dumper:                  0
    Env:                           0
    File::Basename:                0
    File::Path:                    0
    File::Spec:                    0
    File::Temp:                    0
    FindBin:                       0
    Hash::Util:                    0
    IPC::Cmd:                      0
    List::MoreUtils:               0
    List::Util:                    0
    strict:                        0
    Test::Differences:             0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
